### ISSUE TITLE
Data-Oriented programming in Typescript

### ISSUE THREAD

**Issue by viebel** [shybyte/data-oriented-programming-book-experiments#1]
Hello @shybyte,

I am the Author of Data-Oriented programming.

I'd be happy to discuss with you about Data-Oriented programming and Typescript.

If you are interested, please send me an email to schedule a brainstorm session.

You can find my email address on my Github profile.

**Comment by shybyte** [comment]
@viebel Thank you! Have have written a mail to you just now.
